name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: [self-hosted, linux, arm64, build-worker]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Check syntax
        run: npm run check

      - name: Test
        run: npm test
